### ISSUE TITLE
CUBBIT: Identify options on how to connect OCM with CUBBIT

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#10]
As CUBBIT I want my users to be able to share files with other users at other clouds. 
For that, is needed to understand how to fit CUBBIT's access APIs into the protocol extension of the OCM API:
https://rawgit.com/GEANT/OCM-API/v1/docs.html

**Comment by labkode** [comment]
As CUBBIT I want my users to be able to share files with other users at other clouds. 
For that, is needed to understand how to fit CUBBIT's access APIs into the protocol extension of the OCM API:
https://rawgit.com/GEANT/OCM-API/v1/docs.html

**Comment by lposani** [comment]
The major obstacle to overcome is to perform the download and upload from the swarm to a partner client. Partners are supposed to support WebDAV, which is based on HTTP - Cubbit works with an in-house protocol (Cubbit Core) that opens several connections with WebRTC and uses the Cubbit Coordinator server to handle metadata, authorization, security, and handshake.
There are three main possibilities that can be explored to overcome this difficulty:

(1) Cubbit implements a Gateway-Proxy that acts as an endpoint that speaks Cubbit Core on one side and exposes HTTP/WebDAV APIs on the other side. This Gateway-Proxy will be installed as an extra part of the IOP platform. Note that the Gateway-Proxy streams all the downloaded/uploaded data, so we have to consider whether the IOP server itself is able to cover the bandwidth requirements.

(2) Cubbit implements the Gateway-Proxy and puts it as an extra service with a dedicated server. Technologically, this is equivalent to (1) but it will need to assign extra funds to Cubbit to cover the costs for bandwidth streaming on the dedicated server.

(3) Cubbit implements an SDK that can be seamlessly integrated into partners' clients. This will allow download and upload to be performed client-side, avoiding the server Gateway-Proxy costs, but it requires the partners to add the SDK to their software.

Meta-data and authorizations can always be handled through IOP as for other partners. Once we solved the download-upload issue we have to think about how to handle security and encryption keys, as we are currently a zero-knowledge encryption solution and file sharing is performed without letting the provider know the encryption key.

**Comment by labkode** [comment]
As discussing in the meeting on Friday, option (1) is the one that looks more promising and the one to explore.

**Comment by labkode** [comment]
Going forward with option (1)
