### ISSUE TITLE
Add driver to fetch information from GOCDB REST API for providers

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#102]
The current meshdirectory service gets the provider from a JSON file. We need to get this information from the GOCDB REST API, cross-check with @Daniel-WWU-IT for help.

**Comment by Daniel-WWU-IT** [comment]
As mentioned, this functionality will be part of the export service created for #83.

**Comment by mirekys** [comment]
The meshdirectory driver implementation is here [reva.#754](https://github.com/cs3org/reva/pull/754). Location of Mentix API could be configured by setting an URL in service config. I could also modify it to access the export service directly through GRPC when it becomes a part of Reva.

**Comment by mirekys** [comment]
I've been looking into (reva/#755)[https://github.com/cs3org/reva/pull/755] and this driver should already be compatible with HTTP service implemented there.
