### ISSUE TITLE
Prepare and run the WOPI server alongside Reva in containers

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [sciencemesh/sciencemesh#105]
Once the WOPI server has been finished, prepare a containerized version of it that can be deployed alongside Reva (which already is available as a container).

Both containers should then be deployed for further testing and development.

Items to be done:
- [x] Prepare chart/helm for WOPI -> https://github.com/cs3org/charts/pull/10
- [x] Pass the WOPI unit test suite -> [`/test/test_storageiface.py`](https://github.com/cs3org/wopiserver/blob/master/test/test_storageiface.py)
- [x] Integrate in IOP deployment -> `condition:` in IOP `requirements.yaml` -> https://github.com/sciencemesh/charts/pull/6
- [x] Fix bugs/issues found while integrating the deployment with reva/Collabora Code.
- [ ] Documentation -> https://github.com/sciencemesh/sciencemesh/pull/142

**Comment by SamuAlfageme** [comment]
Pinging @labkode for his two-cents on this as we discussed it on the WP4 telco today: once it's finished, shall we add the `wopiserver` chart (https://github.com/cs3org/charts/pull/10) to the IOP, with an additional helm flag to deploy it? (i.e. disabled by default)

**Comment by Daniel-WWU-IT** [comment]
For me this makes sense, as WOPI will be needed by all sites sooner or later. That might also make configuration easier, as you can assume that Reva and the WOPI server are running side by side etc.

**Comment by glpatcern** [comment]
This work is progressing with https://github.com/cs3org/reva/pull/1035 and https://github.com/cs3org/wopiserver/releases/tag/v5.3, which fix a number of issues found in the initial integration tests and remove some TODOs.
