### ISSUE TITLE
Establish connection between Collabora and Reva/WOPI

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [sciencemesh/sciencemesh#107]
Plug both Collabora and Reva/WOPI together so that Collabora will indirectly use Reva via its WOPI server to synchronize data and enable collaborative editing across different sites. This can be done by using a simple `curl` command.

Once established, this feature (i.e., collaborative editing) should first be tested by editing a document by different users **of the same site**.

**Comment by labkode** [comment]
@Daniel-WWU-IT before creating an new issue take a look if they already exist. This one looks like a duplicate of: https://github.com/sciencemesh/sciencemesh/issues/66

**Comment by Daniel-WWU-IT** [comment]
Indeed, will do better next time! This can be deleted then.
