### ISSUE TITLE
Test on-site and federated sharing in Reva

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [sciencemesh/sciencemesh#108]
In order to be able to perform collaborative editing across different sites, federated sharing must be functional in Reva. To test this functionality, it is first necessary to verify it across a single side and afterwards across different ones.

- [x] Deploy latest Reva (required PR just merged today)
- [x] Test WebDAV sharing across two reva daemons. This is supposed to be the OCM example, to be validated.

**Comment by glpatcern** [comment]
Tested right now across CERN and WWU. It works :-) but with a few caveats:
* expiration in the invite token actually is the current time of the request
* user invite workflow should be assumed to be symmetric: if user A invited user B, user B should NOT need to invite user A (assume mutual trust)
* when no invitation has been accepted yet, or if it already has been accepted and one tries to do that again, error code is rather generic: `code=CODE_INTERNAL msg="error fetching remote user details"`
* The invite generation workflow should be wrapped on a Reva command to avoid using cURL
* Inability to navigate to a share if another one is unreachable
* Display of shares produces a waaay too large table:
```
+--------------------------------------+-----------+----------------+------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+-------------------+-----------------+------------------+--------------------------------+--------------------------------+
| #                                    | OWNER.IDP | OWNER.OPAQUEID | RESOURCEID                                                                         | PERMISSIONS                                                                                                     | TYPE              | GRANTEE.IDP     | GRANTEE.OPAQUEID | CREATED                        | UPDATED                        |
+--------------------------------------+-----------+----------------+------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+-------------------+-----------------+------------------+--------------------------------+--------------------------------+
| 0b83eab7-4435-4090-b27d-a9b8702614a6 | cern.ch   | samuel9876     | storage_id:"123e4567-e89b-12d3-a456-426655440000" opaque_id:"fileid-samuel%2Fglp"  | permissions:<get_path:true initiate_file_download:true list_container:true list_file_versions:true stat:true >  | GRANTEE_TYPE_USER | uni-muenster.de | daniel5678       | 2020-09-03 10:58:05 +0200 CEST | 2020-09-03 10:58:05 +0200 CEST |
+--------------------------------------+-----------+----------------+------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+-------------------+-----------------+------------------+--------------------------------+--------------------------------+
```

**Comment by Daniel-WWU-IT** [comment]
Here is another point that should be improved:
- when up-/downloading via the Reva CLI, if no explicit target filename has been specified but only an _existing_ folder, the originating filename should be used for the target. As of now, the folder is replaced by the file, leading to all sorts of problems

**Comment by labkode** [comment]
> * when up-/downloading via the Reva CLI, if no explicit target filename has been specified but only an _existing_ folder, the originating filename should be used for the target. As of now, the folder is replaced by the file, leading to all sorts of problems

@ishank011 this we need to forbid in the implementation.

**Comment by glpatcern** [comment]
For this latter issue, I've reopened https://github.com/cs3org/reva/issues/1032.
For all the others, we still did not go through them but they should essentially become tasks/issues in reva (yeah looks like we're creating work for you guys)

**Comment by ishank011** [comment]
> * when up-/downloading via the Reva CLI, if no explicit target filename has been specified but only an _existing_ folder, the originating filename should be used for the target. As of now, the folder is replaced by the file, leading to all sorts of problems

For this, I'll add the check to prevent the overwriting in https://github.com/cs3org/reva/pull/1140. For deriving the file name in this case, this would need to be carried out on the client side as reva does not get any info about the local file. And we'd need to add this to all the clients. Should we proceed with that? @labkode @glpatcern 

> * the `expiration` field in the invite token actually corresponds to the current time of the request

It returns the current time + expiration (which by default is 24 hours). The token would never be accepted if the expiration was when it was created.

> * the user invite workflow should be assumed to be symmetric: if user A invited user B, user B should NOT need to invite user A (assume mutual trust)

Can be discussed

> * when no invitation has been accepted yet, or if it already has been accepted and one tries to do that again, error code is rather generic: `code=CODE_INTERNAL msg="error fetching remote user details"`

The errors are different. You get this error if the user hasn't accepted the invite. In case of accepting the invite from the same user again, we get `error accepting invite error="json: user already added to accepted users"` on the remote side. On the local side, the error code is not transmitted over HTTP (This is a general fault across reva; error messages get lost in abstractions, need to fix this), so you get
```
{
  "code": "SERVER_ERROR",
  "message": "grpc forward invite request failed"
}
```

> * The invite generation workflow should be wrapped on a Reva command to avoid using cURL

https://github.com/cs3org/reva/issues/1149

> * Inability to navigate to a share if another one is unreachable

Fixed in https://github.com/cs3org/reva/pull/1140

> * When accepting a share, the folder in `/MyShares` is named after the original folder. Need to give the option to name it to the user, to prevent collisions (cf. Dropbox).

Agreed https://github.com/cs3org/reva/issues/1150

**Comment by glpatcern** [comment]
Thanks for all the comments @ishank011.

For using a folder as target, I understand this requires the information to be passed through from all clients, but I guess it's needed as it's a pretty standard expectation to push a file to a folder in this way.

For the `expiration` value, I'll post here what I got once we run the test again with all the fixes.

**Comment by ishank011** [comment]
Owncloud tests expect the overwrite to go through https://cloud.drone.io/cs3org/reva/2470/2/4

**Comment by glpatcern** [comment]
(Prior to closing this, need to add follow up issues in reva as per my last comment)
