### ISSUE TITLE
Test collaborative editing of documents in Collabora across different sites

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [sciencemesh/sciencemesh#109]
To test collaborative editing of a document across different sites, multiple _separated_ sites need to edit a specific document using Collabora **at the same time**, effectively performing the desired federated collaborative editing.

**Comment by glpatcern** [comment]
Pending https://github.com/sciencemesh/sciencemesh/issues/108 and confirmation that federated sharing works properly (work in progress in WP3)

**Comment by glpatcern** [comment]
First test ever of this workflow: currently the request does not go out to the remote reva and fails with e.g.:
```
error: code=CODE_INTERNAL msg="Stat failed on the resource path for the app provider: /home/MyShares/glp/Example.odt" support_trace="8c36b343db0f6f6faf0c5ad38fdcdcd8"
```

**Comment by glpatcern** [comment]
Update: having included https://github.com/cs3org/reva/pull/1140 we have a fully working collaborative editing across CERN and WWU :-)
A remaining issue is with the displayed username, as noted in the PR.

**Comment by glpatcern** [comment]
The remaining issue is now documented in https://github.com/cs3org/reva/issues/1198.
