### ISSUE TITLE
CERN: further value.yaml config options for the revad Helm chart 

### ISSUE THREAD

**Issue by SamuAlfageme** [sciencemesh/sciencemesh#117]
I'm currently working on https://github.com/SamuAlfageme/charts/tree/revad_configmap to determine the best way to configure revad according to https://reva.link/docs/config.

We however might need to move to a helper configmap script + init-container to generate the toml as templating can get a bit complex on nested toml values 😕

**Comment by SamuAlfageme** [comment]
After a little bit of digging, I've only found out a couple of projects that use tomlfiles as config in https://github.com/helm/charts. Here's how they're configuring the deployments with helm:

- **Traefik**: mounting a local `.toml` file via `.Values.configFiles`. This **requires to have the file ready** beforehand - ref. [`traefik/templates/config-files.yaml `](https://github.com/helm/charts/blob/c646e884b3772daa9a012aaf2d4a8df5e8b92a09/stable/traefik/templates/config-files.yaml) 
- **Burrow**: provide some overridable parameters in a `ConfigMap`, but **keep most hardcoded**. This as flexible but if we don't want to configure that many parameters it might be the best way - ref. [`burrow/templates/config-configs.yaml `](https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/incubator/burrow/templates/config-configs.yaml)

Apart from these, I've also realized that the **gitlab-ci runners** use toml config. Found this issue https://gitlab.com/gitlab-org/charts/gitlab-runner/-/issues/83 with some interesting discussion and [a MR with some logic in the `_helpers.tpl` for that.](https://gitlab.com/gitlab-org/charts/gitlab-runner/-/merge_requests/39/diffs)

Also a combination of these methods can be looked into. @labkode from a REVA standpoint, what do you think?

**Comment by labkode** [comment]
@SamuAlfageme 

>     * **Traefik**: mounting a local `.toml` file via `.Values.configFiles`. This **requires to have the file ready** beforehand - ref. [`traefik/templates/config-files.yaml `](https://github.com/helm/charts/blob/c646e884b3772daa9a012aaf2d4a8df5e8b92a09/stable/traefik/templates/config-files.yaml)

This is the option I prefer the best. Simple and powerful. I'm old school :)

If we go that path, what would be the helm commands to run it with a default out of the box configuration and the command with a custom config?


```
helm install --name my-release

**Comment by SamuAlfageme** [comment]
@labkode sounds reasonable, I also reckon it's a good way to go as we can provide more than one config file. Dummy example:

```yaml
configFiles:
  revad.toml: |
    [shared]
    jwt_secret = "mysecret"

    [http]
    address = "0.0.0.0:20080"

    [http.services.prometheus]

    [grpc]
    address = "0.0.0.0:20099"
  providers.json: |
    [
      {
        "domain": "cern.ch",
        "api_version": "0.0.1",
        "api_endpoint": "http://127.0.0.1:13001/ocm/",
        "webdav_endpoint": "http://127.0.0.1:13001/ocm/webdav/"
      }
    ]
```

### Run it with defaults: 
```console
$ helm install revad cs3org/revad
```

> what would be the helm commands to run it with a **default out of the box configuration**

Q: What do we want as _out-of-the-box_ defaults? `jwt_secret` and `[http]` + `[grpc]` bound to the service ports?

### Override `revad.toml`:
```console
$ helm install revad cs3org/revad - f custom-config.yaml
```
