### ISSUE TITLE
Update authentication in cs3iface in WOPI server.

### ISSUE THREAD

**Issue by LovisaLugnegard** [sciencemesh/sciencemesh#118]
Currently the authentication is hardcoded to be einstein and relativity, this should not be the case. In file cs3iface.py in WOPI repo.

**Comment by glpatcern** [comment]
As I see things now, it turns out that we just have to use the x-access-token that is (going to be) passed to the `/open` call being worked on. I will commit a fix on the WOPI server that removes much of the logic around authentication.
