### ISSUE TITLE
CERN: implement the WOPI `/open` call in Reva

### ISSUE THREAD

**Issue by glpatcern** [sciencemesh/sciencemesh#121]
The CS3 APIs already provide this endpoint:

https://cs3org.github.io/cs3apis/#cs3.app.provider.v1beta1.OpenRequest

This needs to be changed such that:
- [x] `resource_info` becomes a `ref`, like for other file-oriented APIs
- [x] an extra enum `viewmode` argument is added
- [x] Add open call for reva to api gateway
- [x] Implement open cmd in reva - possibly with the extra bonus of firing the client's browser with the URL received in the response.
- [x] Test WOPI server together with reva locally

The implementation in Reva is basically as follows:
1. Get the application URL for the file's mimetype. This is going to be the "Bring Your Own App registry" service in Reva, for now it's implemented by the wopiserver at `/wopi/cbox/endpoints`.
2. Call the wopiserver's `/wopi/iop/open` and pass the requested arguments (documented at https://github.com/cs3org/wopiserver/blob/master/src/wopiserver.py#L238).
3. Output all as the `iframe_url` field of the `OpenResponse`. For reference, +https://github.com/cs3org/wopiserver/blob/master/tools/wopiopen.py does a similar job.

**Comment by labkode** [comment]
@glpatcern about the mode, a view-only mode is foreseen for GDPR/OC11 rules, so the "mode"  would be better an enum.

**Comment by glpatcern** [comment]
@labkode fine with me, what is the difference between view-only and read-only? maybe downloadable is part of read-only but not view-only, or what else?

**Comment by labkode** [comment]
@glpatcern yes, exactly that

**Comment by glpatcern** [comment]
Very good, then I suggest to have a non `required` field, default to `view-only` (minimal permissions). 

Given that changing the `required` `resource_info` field is giving some headaches to @LovisaLugnegard, let's not introduce yet another one.
