### ISSUE TITLE
CERN: Create new OCM UI-only app to accept invites 

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#13]
(SUBTASK to CERN: Extend OCM with Invitation Flow #4)

Add a UI in Phoenix to accept an invitation. A first step is a button and a field where the user can type in their access token.

In practice this means creating a new oc app.

**Comment by LovisaLugnegard** [comment]
I've a WIP PR https://github.com/owncloud/phoenix/pull/3203, please have a look @labkode and @ishank011

**Comment by LovisaLugnegard** [comment]
I've created a new app for this feature https://github.com/sciencemesh/accept-invite

**Comment by labkode** [comment]
Prototype done.
