### ISSUE TITLE
CESNET: develop Reva extension for provider metadata

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#17]
This task will produce a new HTTP service that will expose a simple UI with a list of the providers available in the mesh. The user will choose theirs and the user will be sent to that sync'n'share provider.

Create the new service using the *helllo* service as an example:
https://github.com/cs3org/reva/tree/master/internal/http/services/helloworld.

To fetch metadata, use a JSON file for time being where the endpoints will be defined, you can take a look how is done here for easy switch between different implementations.

You define an interface with the necessary functions to fetch provider metadata:
https://github.com/cs3org/reva/blob/master/pkg/ocm/share/share.go#L29

and then you do the implementations:
https://github.com/cs3org/reva/tree/master/pkg/ocm/share/manager

We can call this new component:
*meshdirectory*

**Comment by mirekys** [comment]
Hello @labkode, is the correct place for the MeshProvider metadata model putting it into the cs3apis (like the [Share](https://github.com/cs3org/cs3apis/blob/master/cs3/sharing/ocm/v1beta1/resources.proto#L38) is) or can this model be local just for the extension? I have it in the `pkg/meshdirectory/meshprovider.go` for now just like this:
```
type MeshProvider struct {
	ID          string `mapstructure:"id"`
	Org         string `mapstructure:"org"`
	Name        string `mapstructure:"name"`
	Description string `mapstructure:"description"`
	Logo        string `mapstructure:"logo"`
	Homepage    string `mapstructure:"homepage"`
	OCM         string `mapstructure:"ocm"`
}
```
Thanks :)

**Comment by labkode** [comment]
Hi @mirekys I think is okay where you have it, later on we can see if we can have a common package for OCM and this service.

**Comment by ishank011** [comment]
Hi @mirekys and @labkode, we already have a pkg which checks if a provider is registered in the mesh or not: https://github.com/cs3org/reva/blob/master/pkg/ocm/provider/provider.go, based on the CS3 definitions: https://cs3org.github.io/cs3apis/#cs3.sharing.ocm.v1beta1.ProviderInfo. An example of the list of providers can be found at https://github.com/cs3org/reva/blob/master/examples/ocmd/providers.demo.json

I think it would be a good idea to modify the API resource definition to include the additional fields and add it here only. We could add a method which returns the list of all providers. Please let me know your thoughts about this.

**Comment by mirekys** [comment]
@ishank011 that sounds good to me, I have already done the listing method, so I can move it under `ocm/provider/`

**Comment by labkode** [comment]
@mirekys @ishank011 nice work! @mirekys also for such service add a method to get some HTML out of it to present to the user not a JSON dump but a `<select>` so when the user chooses the page will redirect them to corresponding provider.

Doesn't need to be beautiful ;)

**Comment by mirekys** [comment]
No problem, will do some simple ui for it :) I could also try to extend and reuse the existing `ProviderInfo` cs3apis definition with some Opaque field, so additional fields could be passed in, like @ishank011 suggested. Then I could also move the [GetMeshProviders](https://github.com/cs3org/reva/pull/626/files#diff-56edf11cf6e373fb1bebe26e48c4be0bR24) method to the `ocm/provider` and the `meshdirectory` module would then be responsible just for a handling of http (ui), is that ok for you @ishank011 @labkode?

**Comment by ishank011** [comment]
@mirekys Sounds good! And rather than just the opaqueID, maybe you can add them as separate fields, because it would make sense to have those - your call.

**Comment by mirekys** [comment]
@labkode I added the UI part [here](https://github.com/cs3org/reva/pull/626/commits/9fe886ec71fd1469f83e9b9e97a2d6c5cd7c3580), please have a look :). I was not sure where to put the `index.html`, so I left it in `examples` and made the whole `static` folder location configurable at least. So the UI part could be separated later on, if needed. I decided to go with VueJS as that would make things like provider filtering/searching & cookies manipulation (bookmarking providers,...) much easier to implement in the future.

**Comment by labkode** [comment]
Nice job, we'll iterate on it later on.
