### ISSUE TITLE
sciencemesh documentation

### ISSUE THREAD

**Issue by marqsbla** [sciencemesh/sciencemesh#203]
I just have limited time to scan through docs. I focused on checking if links are working and technical staff. In these places there is a lot of repetition, the repetition is made in a way, that the repeted things are often wrong or contradictory to each other. Once we ask to clone the app, then we write, that for production only download from the appstore, etc. Also the reva configuration in ALL places is obsolete. I founded the reference to reva documentation in at least 5 different sites. All deprecated:
https://developer.sciencemesh.io/docs/technical-documentation/iop/iop-nextcloud-owncloud10-integrations/
https://developer.sciencemesh.io/docs/technical-documentation/efss-deployment/manual-efss-installation/
https://developer.sciencemesh.io/docs/technical-documentation/iop/deployment/
https://developer.sciencemesh.io/docs/technical-documentation/iop/configuration/
https://developer.sciencemesh.io/docs/technical-documentation/iop/iop-nextcloud-owncloud10-integrations/
and this is only on the "blessed path". And I haven't found a single reference to latest config file:  https://raw.githubusercontent.com/cs3org/reva/master/examples/sciencemesh/sciencemesh.toml

Below some quick comments of what I found. 
1.  https://developer.sciencemesh.io/docs/architecture/central-component-implementation/
Blackbox Exporter has broken links
2. https://developer.sciencemesh.io/docs/how-to-join-sciencemesh/ this is the page that is pointed as starting point of installation
is pointing to effs deployment which are very obsolete, look below
it also says all about patches
reva version, from what I know, should be 1.26
maybe point to blessed version from this page?
3. https://developer.sciencemesh.io/docs/technical-documentation/efss-deployment/
obsolete configuration, via database
4. https://developer.sciencemesh.io/docs/technical-documentation/efss-deployment/manual-efss-installation/
no patches required
5. https://developer.sciencemesh.io/docs/technical-documentation/iop/iop-nextcloud-owncloud10-integrations/ 
the patch is there in nc 27.1.2. 
the blessed version are onluy here, the rest after "Inter-Operability Platform/Reva Integrations with Nextcloud and ownCloud10 " is obsolete. 
6. https://developer.sciencemesh.io/docs/technical-documentation/iop/deployment/
very, very, very obsolete configuration file and all deployment as well. 
7. https://developer.sciencemesh.io/docs/technical-documentation/iop/configuration/
very obsolete configuration. It has been fixed and simplified:
https://raw.githubusercontent.com/cs3org/reva/master/examples/sciencemesh/sciencemesh.toml

**Comment by marqsbla** [comment]
In the "overall description" I havn't found any big mistakes. I wasn't looking that deeply though.

**Comment by glpatcern** [comment]
Thanks @marqsbla, definitely appreciated. Now if you can also submit a PR at least with the "easy" things (e.g. removing all pages that are obsoleted), it would be great.

**Comment by milkydan** [comment]
I have polished the documentation based on this issue, so I believe that I have resolved all the reported stuff even more :smile: 
Corresponding PR: https://github.com/sciencemesh/sciencemesh/pull/204

**Comment by marqsbla** [comment]
thanks. sorry, I have busy days lately :/
