### ISSUE TITLE
AILL&CERN: Implement existing OCM (share API only)

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#3]
Implement the OCM protocol as Reva HTTP service: 

https://github.com/cs3org/reva/pull/558

- [x] add to the reva-cli the commands ocm-share-create ocm-share-list, etc, ... as done for normal shares
- [x]  implement the ocmprovider,  similar to https://github.com/cs3org/reva/tree/master/internal/grpc/services/usershareprovider
- [x] implement the ocmd http service, already started here: https://github.com/cs3org/reva/pull/558

**Comment by JarCz** [comment]
ishank011: 
* add share - endpoint: POST /shares

JarCz:
* list shares - endpoint: GET /shares
* get share - endpoint: GET /shares/{id}

**Comment by labkode** [comment]
PR merged.
