### ISSUE TITLE
SURFSARA: add a new service to Reva to expose desired metrics

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#30]
This task will produce a new HTTP service that will expose the metrics described in:
https://github.com/sciencemesh/sciencemesh/issues/8

Create a new service using the hello service as an example:
https://github.com/cs3org/reva/tree/master/internal/http/services/helloworld.

For example:
https://github.com/cs3org/reva/tree/master/internal/http/services/cs3meshmetrics.

**Comment by rontrompert** [comment]
HTTP serrvice will expose the following metrics:

    

-     Number of users per site
-     Number of groups per site
-     Amount of used storage per site
-     Number of local shares per site
-     Number of shares between federated sync-and -share services
-     Local application usage per site
-     Cross-site application usage
