### ISSUE TITLE
AILL: Use ConfigMap for revad and phoenix in k8s/minikube

### ISSUE THREAD

**Issue by ebocchi** [sciencemesh/sciencemesh#38]
Related to https://github.com/sciencemesh/sciencemesh/pull/14

We should consider to have the config passed as ConfigMap rather that making the config file part of the image.

**Comment by SamuAlfageme** [comment]
Closing as done in https://github.com/sciencemesh/sciencemesh/pull/42/commits/e58c924dec536821c0c1047fb3898595c90c2172
