### ISSUE TITLE
CERN: Prototype extension of OCM with Invitation Flow

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#4]
As user of a cloud system I want to easily shares with other user at other clouds. 
However I don't want my cloud admin to export automatically my personal contact address. I want to receive an invitation and decide under which cloud I'm part of I want to access the shared information.

For that I need an invitation mechanism.  

The idea is to extend the existing OCM protocol with an invitation endpoint:
https://github.com/GEANT/OCM-API/pull/39

**Comment by LovisaLugnegard** [comment]
Can this ticker be divided into smaller pieces? Eg. one for defining the endpoint and then one ticket per endpoint to implement?

**Comment by labkode** [comment]
@LovisaLugnegard, sure please do

**Comment by labkode** [comment]
PR created.
