### ISSUE TITLE
CUBBIT: create stub NodeJS server for OCM

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#44]
Based on:
https://cs3org.github.io/cs3apis/#cs3%2fsharing%2focm%2fv1beta1%2focm_api.proto

Diagrams here:
https://github.com/sciencemesh/sciencemesh/issues/16#issuecomment-613925994

We implement the consumer part only, and only these methods:
CreateOCMShare, GetOCMShare and ListOCMShares.

CS3APIs for JS are generated here:
https://github.com/cs3org/js-cs3apis

If those generators will not work, let see how you can add the necessary generators to the CS3APIS.

**Comment by alessandro-p** [comment]
@labkode You can find the repo [here](https://github.com/cubbit/cubbit-iop). Let me know if you have any feedback.

**Comment by labkode** [comment]
@alessandro-p , thank you, it looks good.
