### ISSUE TITLE
WWU: add GOCDB to ScienceMesh as Docker container

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#47]
Package the GOCDB deployment into a K8s chart and add it here:
https://github.com/sciencemesh/sciencemesh/tree/master/k8s/reva-phoenix

**Comment by Daniel-WWU-IT** [comment]
@labkode This might take a bit, as I don't know anything at all about Kubernetes and will have to learn the basics first. Would be glad if you could maybe point me in the right direction where to start and what you expect. How, let's say, "production ready" shall this instance be? Should it be deployed with some data, or should it be just an empty playground? My own GOCDB test suite uses a super crude authentication method (that is, a workaround to avoid it at all), but that also renders some features (user roles, mainly) unfunctional.

So my questions before I can start are as follows:
- A pointer in the right direction from where to start with Kubernetes
- Whether a simple authentication method (a better one than the workaround I'm using for testing, of course) is enough for now, or if you want something more sophisticated
- If you want an empty GOCDB users can fill on their own (it's really simple and intuitive), or if you want to have some data prefilled (and if so, what data you'd imagine to be added to it by default)
- Anything else you might have in mind

Also, should it really be added under reva-phoenix?

**Comment by labkode** [comment]
> @labkode This might take a bit, as I don't know anything at all about Kubernetes and will have to learn the basics first. Would be glad if you could maybe point me in the right direction where to start and what you expect. How, let's say, "production ready" shall this instance be? Should it be deployed with some data, or should it be just an empty playground? My own GOCDB test suite uses a super crude authentication method (that is, a workaround to avoid it at all), but that also renders some features (user roles, mainly) unfunctional.
> 
> So my questions before I can start are as follows:
> 
> * A pointer in the right direction from where to start with Kubernetes
First of all, play with the existing setup:
https://developer.sciencemesh.io/docs/iop/deployment/minikube/

To learn:
https://helm.sh/ and base your charts on the ones that are already there.
 @SamuAlfageme @ebocchi @mateusz-garlacz  can give you hints if you're blocked.

> * Whether a simple authentication method (a better one than the workaround I'm using for testing, of course) is enough for now, or if you want something more sophisticated

This is for an MVP of what to send to ARGO, so no auth is needed at this stage at all.

I expect something like an admin will have a list of endpoints defined in a config file or to run some commands to add new endpoints to the database.

> * If you want an empty GOCDB users can fill on their own (it's really simple and intuitive), or if you want to have some data prefilled (and if so, what data you'd imagine to be added to it by default)

An admin will fill new endpoints.

> * Anything else you might have in mind
> 
> Also, should it really be added under reva-phoenix?

Yes, the reva-phoneix name needs to be changed to sciencemesh, sciencemesh is more than just reva+phoenix and phoenix is there only for convenience to an UI to browse on Reva but is not part of the sciencemesh project.

**Comment by Daniel-WWU-IT** [comment]
@labkode The Docker files are now ready. I think to be able to provide them via Helm charts, the images need to be uploaded to the Docker Hub, but I'm not sure if this is actually ok, especially for EGI. They don't contain anything private, but you never know... so maybe we should check this first?

**Comment by labkode** [comment]
Hi @Daniel-WWU-IT, we'll push the images to DockerHub but we'll to that in the CI/CD pipeline that we already have setup for others repo, you don't need to do that yourself. We need to improve the packaging you've done, specially the installation of the web files that you are copying into the container. Let's have a chat this week to clarify this area.

**Comment by Daniel-WWU-IT** [comment]
Sounds good. Since these are my first containers, it's likely that they aren't perfect right from the start. I also have to make the database instance configurable via env. variables in the GOCDB configuration.

**Comment by Daniel-WWU-IT** [comment]
I updated a few things in my fork. The container files now work quite well in Minikube (I also included the k8s files I used for that, even though they are not ready for deployment).

**Comment by labkode** [comment]
@Daniel-WWU-IT in the Docker container can you run a `apt-install` or `wget & unzip` to get the required files? Like that the Docker spec is much cleaner and easier to understand.

**Comment by Daniel-WWU-IT** [comment]
The files are modified (GOCDB requires configuration files to be added/modified). This is why it seemed to me that the best way to provide the files is to simply add them in the repo and copy them into the container. Another reason for this is that these files are for testing and playing around only, so I wanted to add the sources directly. I think uploading them to somewhere and downloading them via _wget_ is also feasible, but I'd need some webspace for that where I can put them online.

**Comment by labkode** [comment]
Closing, we'll follow up on other sub-issues
