### ISSUE TITLE
CERN: Document local deployment of the IOP

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#5]
As a site admin or a developer I want to be able to install the IOP.

For that  I need instructions. 

This task creates a tutorial on how to deploy the IOP locally on a computer from the different software repositories (Reva, ...) and using the ownCloud Phoenix UI to be able to easily browser files from a web browser.

**Comment by LovisaLugnegard** [comment]
The PR is here https://github.com/cs3org/reva/pull/561

**Comment by labkode** [comment]
PR merged
