### ISSUE TITLE
CERN: create sciencemesh/chart registry and consume Reva's from cs3org/chart 

### ISSUE THREAD

**Issue by SamuAlfageme** [sciencemesh/sciencemesh#53]
As an operator of ScienceMesh and external user I want to be able to use these charts to deploy the platform. 

```
helm repo add sciencemesh https://sciencemesh.github.io/charts/
```

to have a list of all the charts available there, like e.g. IOP, central-brain...

**Comment by labkode** [comment]
@SamuAlfageme here we should not define again the Reva chart, but use it, is that possible?

**Comment by SamuAlfageme** [comment]
@labkode Indeed, you're right. Bad phrasing. We'll define Reva as [a dependency](https://helm.sh/docs/helm/helm_dependency/) for the sciencemesh chart.
