### ISSUE TITLE
CERN: fix python cs3apis generator

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#54]
As a developer I want to import the cs3 apython APIs:

```
import cs3.gateway.v1beta1.gateway_api_pb2 as cs3gw
import cs3.gateway.v1beta1.gateway_api_pb2_grpc as cs3gw_grpc
```

However this will only work is each python module contains an the following file:
```
__init__.py
```

So in practical terms when building the APIs we need to add this file on the following folder and subfolders recursively.

```
https://github.com/cs3org/python-cs3apis/tree/master/cs3
```

To add this file you need to modify the cs3apis-builder docker image in this place to create those files:

```
https://github.com/cs3org/cs3apis-build/blob/master/build.go#L361
```

**Comment by LovisaLugnegard** [comment]
I don't think we need to do this. The empty `__init__.py` files are not needed since python 3.3, and I suggest we shouldn't support python 2 at all since the sunset for it was January 2020. (https://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3-3)

**Comment by labkode** [comment]
@LovisaLugnegard okay, then I think this issue can be closed, if you think documentation is necessary add it directly in the readme of the python-cs3apis repository.
