### ISSUE TITLE
May IOP Deployment

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#78]
IOP v0.0.1
[Deployment documentation](https://developer.sciencemesh.io/docs/iop/deployment/minikube/)

- [ ] AILLERON
- [ ]  WWU
- [ ] CERN
- [ ] PSNC
- [ ] CESNET
- [ ] SURFSARA
- [ ] DTU
- [ ] AARNET
- [ ] CUBBIT

[Feedback for deployment](https://github.com/sciencemesh/sciencemesh/issues/new)

**Comment by rontrompert** [comment]
All partners on this list have been contacted.

**Comment by rontrompert** [comment]
Installed by WWU+SURFsara (still need to do the ingress)

**Comment by rontrompert** [comment]
Pinged everyone again

**Comment by rontrompert** [comment]
current status:
Deployed: CESNET, SURFsara, WWU
The rest is still in progress.

**Comment by labkode** [comment]
@rontrompert can you get the public urls?

**Comment by mirekys** [comment]
@labkode CESNET: https://sciencemesh.cesnet.cz

**Comment by Daniel-WWU-IT** [comment]
@labkode WWU: https://sciencemesh-test.uni-muenster.de (uploads are not working atm)

We are also running an instance of the GOCDB here:
https://sciencemesh-test.uni-muenster.de/gocdb

**Comment by labkode** [comment]
Deployment information can be found here:
https://wiki.cs3mesh4eosc.eu/wps/3/deployments
