### ISSUE TITLE
SURFSARA: Identify metrics for accounting

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#8]
As a site administrator I want to be sure I can comply with the SLA of the service and for that  I need to monitorise the performance of it.

For such to happen, I need to identify the metrics/KPIs (number of shares, latency, ...) 

Be creative :)

**Comment by rontrompert** [comment]
Looking at the project proposal and the KPIs defined in there that relate to accounting, we have come up with the following:

1. Number of users
2. Number of groups
3. Amount of storage per site
4. Number of local shares
5. Number of shares between federated sync-and -share services
6. Local application usage
7. Cross-site application usage

None of these can be regarded as personal data, so we will have no issues with GDPR compliance here. 

In addition to this, you could think of having the numbers above also for every community, but I am not sure if this is going to be feasible or too much work or whatever. 

But what is your opinion on this?

**Comment by labkode** [comment]
Metrics identified.
