### ISSUE TITLE
CERN: package CS3APIs bindings

### ISSUE THREAD

**Issue by glpatcern** [sciencemesh/sciencemesh#80]
- [x] Python: need to create a pip package, so that e.g. the wopiserver can `pip install cs3apis`. Instrumental to #56. -> https://github.com/cs3org/python-cs3apis/pull/1
- [x] Go: no special packaging needed thanks to Golang
- [x] ~Javascript: npm package~ -> https://github.com/sciencemesh/sciencemesh/issues/115

**Comment by labkode** [comment]
For this task @SamuAlfageme can give you a hand as I expect this to be automated, meaning any merged PR to the master branch will create a "latest" release in PIP.

**Comment by SamuAlfageme** [comment]
It can be as we do for the docker builds on the [cs3org/cs3apis-build pipeline](https://github.com/cs3org/cs3apis-build/blob/master/.drone.yml) 

I've seen the org is already provisioned on: 
- https://www.npmjs.com/org/cs3org
- https://pypi.org/user/cs3org

Are these right?

**Comment by labkode** [comment]
@SamuAlfageme yes, I reserved those long time ago. Let me find the credentials

**Comment by glpatcern** [comment]
Excellent @SamuAlfageme, at this point I leave this to you :) and what about JavaScript bindings? Does that need to be packaged as well?

**Comment by labkode** [comment]
@alessandro-p for the Javascript bindings, I think you can help us here as you mentioned that having Typescript support will help. We may need to help here.

**Comment by SamuAlfageme** [comment]
@alessandro-p for the time being, would it help if we publish the contents of `cs3` from https://github.com/cs3org/js-cs3apis after running `npm init` to add the missing metadata?

**Comment by alessandro-p** [comment]
Hi guys, here I am. Sorry for the late answer. Right now we made a basic `make.js` script that uses first pbjs and then pbts to generate protos and their type definitions. You can find the script [here](https://github.com/cubbit/cubbit-iop/blob/master/make.js). 

@SamuAlfageme what do you mean with 'adding the missing metadata'?

**Comment by SamuAlfageme** [comment]
@alessandro-p ah, I see. You're generating the cs3apis bindings in JS by yourself instead of using 
https://github.com/cs3org/js-cs3apis. By metadata I meant the missing `package.json` for `cs3org/js-cs3apis`.

@labkode should we do the same (run`pbts` after `protoc`) in [cs3apis-build's `buildJS()`](https://github.com/cs3org/cs3apis-build/blob/master/build.go#L369-L396)?

**Comment by labkode** [comment]
@SamuAlfageme I think we can add the pbts build there also and generate the ts code under a different folder maybe? In existing Js libraries that has support also for TS how is the code organized? @alessandro-p

**Comment by alessandro-p** [comment]
We prefer keeping the *d.ts files inside the same directory as the *.js. 

For example:
![image](https://user-images.githubusercontent.com/17408784/81787519-79d92000-9501-11ea-8cad-5dea7101a1e4.png)
