### ISSUE TITLE
Add Export script as a Reva background service

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#83]

**Comment by Daniel-WWU-IT** [comment]
@labkode What would be the best way to add such a background service to Reva? I currently only see HTTP and GRPC services. The service does offer an HTTP endpoint, so I could add it that way and have a background thread doing the "other" stuff (pulling data, exporting it to Prometheus etc.), but I am not sure if this is the best way to do this in Reva. What would you suggest?

**Comment by Daniel-WWU-IT** [comment]
Created this PR: https://github.com/cs3org/reva/pull/755
Will need to change a few things to make lint happy I suppose.
