### ISSUE TITLE
CESNET: Analyse suitability of WAYF vs create a REVA extension

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#9]
As a user of the ScienceMesh I don't want to type server names when connecting to the mesh with my home provider.

For example, I can touch a file and click "Open in Dropbox". I want the same for ScienceMesh.

For that to happen, the user will be sent to a portal to choose from a list of trusted sites (the mesh) to chose from. On clicking the provider, the user will reach the provider AAI system and provide the pertinent login (using any auth the provider offers locally).

It is important that WAYF can handle redirections to the home provider correctly, the use case is the following.

The invitation mail to the target user will be something alike:

```
Dear XXX,

click in this link to access the folder from your cloud:

GET https://hello.sciencemesh/ocm/invitation/forward?token=xyz&origin=https://owncloud.cesnet.cz/
```

The portal mentioned above will be presented to the user, and the GET request will go the home provider AAI:

```
GET cernbox.cern.ch/omc/invitation/forward?token=xyz&origin=https://owncloud.cesnet.cz
```

So the invitation can hit the new OCM endpoint at the target system to accept the invitation.

**Comment by david-antos** [comment]
Hugo, Mirek is studying REVA and we've discussed the use case. I'd like to clarify whether we understand your intentions correctly. In the "invitation to a share via email" scenario, we've described the procedure as "... and the target user receives an email containing link to a WAYF-like web service to choose the target system and then logs in...". So is this intended to provide an alternative like this:

Besides a link to the Central Component “WAYF” service, the invitation email can contain a special URI with a type registered to the sync’n’share client installed at the user’s computer. By clicking the URI, the user triggers the sync’n’share client (in case of multiple systems installed, the user is asked by the system which client should be triggered). By choosing the client, the “WAYF” question is essentially answered and the process continues as described above. The main advantage of this approach is that the user does not have to log into the web interface of the target sync’n’share system, making the procedure much more convenient especially on phones or tablets.

Is this what you had in mind?

**Comment by david-antos** [comment]
And could you please assign Mirek Bauer and Milan Danecek here as well?

**Comment by labkode** [comment]
> Besides a link to the Central Component “WAYF” service, the invitation email can contain a special URI with a type registered to the sync’n’share client installed at the user’s computer. By clicking the URI, the user triggers the sync’n’share client (in case of multiple systems installed, the user is asked by the system which client should be triggered). By choosing the client, the “WAYF” question is essentially answered and the process continues as described above. The main advantage of this approach is that the user does not have to log into the web interface of the target sync’n’share system, making the procedure much more convenient especially on phones or tablets.

Hi @david-antos @berosek  @mirekys , that isn't what I had in mind. What I had in mind is the central WAYF component. The alternative that you propose is appealing and it could be explored in the future. I agree that access to the OCM shares will be more accessible for end-users, and both alternatives are not exclusives.

The alternative that you propose is not on the critical path for delivering the MVP because:
* needs developments from vendors (and they will be exposed to the final APIs on M9)
* web-only users will be excluded with this approach as they don't have a sync client.

So please focus on the central component use-case  and the analysis of the WAYF software to create this central provider service.

**Comment by mirekys** [comment]
Hi @labkode, as for the existing WAYF software, we found and looked into the following solutions:

eduID/eduGAIN WAYF
------------------------------
https://wiki.geant.org/pages/viewpage.action?pageId=88769546
https://github.com/CESNET/wayf
https://www.eduid.cz/cs/tech/wayf

Technology: **PHP, JS, SAML2.0**

A PHP based WAYF for choosing the providers (Identity Providers, IdPs) obtained from the edu{ID,GAIN} federation metadata (in SAML 2.0). Has support for creating links for filtering the providers in WAYF. Designed for federated user authentication on Service Providers using Shibboleth or SimpleSAMLphp. I see no easy way to modify this to a simple site catalog based WAYF.

Django WAYF
-------------------
https://github.com/hpcugent/django-wayf

Technology: **Python, Django, SAML2.0**

A Django WAYF app, that uses IdP and SP (Service Provider) metadata from a SAML formatted XML file. Its primary use-case is also the federated Shibboleth SSO. I think there is a lot of site specific and IdP based stuff, that we don't need for our use case.

WAYFHybrid
-----------------
https://github.com/wayf-dk/wayfhybrid

Technology: **Go, SAML2.0**

WAYF service written in Go, dependent again on SAML federation medadata and possibly too much of an overkill for what we need :)


Reva
-------
I believe that a simpler and more flexible solution would be to develop a REVA http service that fetches provider metadata from a configurable service metadata store (etcd, Consul, another kv stores, json...?) and presents them on some API endpoint. Then there could be a simple SPA web app, that fetches the metadata from this endpoint and does all the rendering and redirection of the users based on their choice.

Any comments are welcome :)

**Comment by labkode** [comment]
Targeting an MVP, I propose we go for the last option. Also, OpenIDConnect is the AAI system that is taking over SAML, so using WAYF wil not be the smartest decision long term.
