### ISSUE TITLE
Create configuration repo for the artificial site and central brain on AILL K8s cluster

### ISSUE THREAD

**Issue by labkode** [sciencemesh/sciencemesh#98]

**Comment by SamuAlfageme** [comment]
@dagl about the GitOps model we were discussing yesterday; this is the project we're looking into right now https://github.com/fluxcd/flux. Can see it in action on https://www.youtube.com/watch?v=g9FQxzK9E_M

**Comment by SamuAlfageme** [comment]
We'll use https://github.com/cernbox/iop-config as the reference config repo for CERN's IOP.
